export type DOWNLOAD_MANAGER_STATUS_TYPE = {
  [x: string]: string | undefined
}

export const DOWNLOAD_MANAGER_STATUS: DOWNLOAD_MANAGER_STATUS_TYPE  = {
  '1008':'ERROR_CANNOT_RESUME',
  '1007':'ERROR_DEVICE_NOT_FOUND',
  '1009':'ERROR_FILE_ALREADY_EXISTS',
  '1001':'ERROR_FILE_ERROR',
  '1004':'ERROR_HTTP_DATA_ERROR',
  '1006':'ERROR_INSUFFICIENT_SPACE',
  '1005':'ERROR_TOO_MANY_REDIRECTS',
  '1002':'ERROR_UNHANDLED_HTTP_CODE',
  '1000':'ERROR_UNKNOWN',
  '3':'PAUSED_QUEUED_FOR_WIFI',
  '4':'PAUSED_UNKNOWN',
  '2':'PAUSED_WAITING_FOR_NETWORK',
  '1':'PAUSED_WAITING_TO_RETRY',
  '16':'STATUS_FAILED',
  '8':'STATUS_SUCCESSFUL',
};

